version: '3'
services:
    ws:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
      - 8080:8080
      - 80:80
    rabbitmsq:
      image: rabbitmq:3-management-alpine
      ports:
      - 15672:15672
      - 5672:5672